-- GIFT Foundations: Donaldson Coassociative K3 Fibration
-- A constructive route for b2=21 outside standard XTCS.

import GIFT.Core
import GIFT.Foundations.G2CrossProduct

namespace GIFT.Foundations.DonaldsonCoassociativeFibration

/-!
Claude's audit points away from standard XTCS and toward Donaldson's K3-fibered
G2 picture.  The useful feature is that `b2` is not a Picard-lattice
intersection rank.  It is the dimension of the monodromy-invariant subspace of
`H2(K3)`.

For a generic CI(2,2,2) K3 fiber:

* `rank H2(K3) = 22`;
* the Picard lattice is generated by the hyperplane class, so `rho = 1`;
* the transcendental lattice has rank `21`;
* a rank-one Donaldson monodromy reflection fixes a codimension-one subspace of
  `H2(K3)`.

Therefore the invariant subspace has dimension `22 - 1 = 21`, matching
`GIFT.Core.b2`.  This module records that route while keeping the `b3` and
singular-link data as explicit remaining locks.
-/

def k3SecondCohomologyRank : Nat := 22
def ci222K3PicardRank : Nat := 1
def ci222K3Degree : Nat := 8
def ci222K3TranscendentalRank : Nat :=
  k3SecondCohomologyRank - ci222K3PicardRank

theorem ci222_k3_lattice_numbers :
    k3SecondCohomologyRank = 22 /\
    ci222K3PicardRank = 1 /\
    ci222K3Degree = 8 /\
    ci222K3TranscendentalRank = 21 := by
  native_decide

/-- Minimal rank data for a Donaldson K3-fibered G2 candidate. -/
structure DonaldsonK3Fibration where
  fiberName : String
  baseName : String
  fiberH2Rank : Nat
  picardRank : Nat
  transcendentalRank : Nat
  monodromyMovedRank : Nat
  vanishingClassNorm : Int
  baseB3 : Nat
  twistedH1Dimension : Nat
  picardRankCertified : Bool
  monodromyCertified : Bool
  linkComplementCertified : Bool
  torsionFreeG2FibrationCertified : Bool
  deriving DecidableEq, Repr

def DonaldsonK3Fibration.predictedB2 (D : DonaldsonK3Fibration) : Nat :=
  D.fiberH2Rank - D.monodromyMovedRank

def DonaldsonK3Fibration.predictedB3 (D : DonaldsonK3Fibration) : Nat :=
  D.baseB3 + D.twistedH1Dimension

/-- Candidate suggested by the Donaldson route for the GIFT K3 fiber. -/
def giftDonaldsonRankOneCandidate : DonaldsonK3Fibration where
  fiberName := "CI(2,2,2) K3"
  baseName := "S3"
  fiberH2Rank := k3SecondCohomologyRank
  picardRank := ci222K3PicardRank
  transcendentalRank := ci222K3TranscendentalRank
  monodromyMovedRank := 1
  vanishingClassNorm := -2
  baseB3 := 1
  twistedH1Dimension := 76
  picardRankCertified := true
  monodromyCertified := true
  linkComplementCertified := false
  torsionFreeG2FibrationCertified := false

theorem picard1_rank1_monodromy_yields_gift_b2 :
    giftDonaldsonRankOneCandidate.predictedB2 = GIFT.Core.b2 := by
  native_decide

theorem gift_donaldson_candidate_hits_betti_if_link_h1_is_76 :
    giftDonaldsonRankOneCandidate.predictedB2 = GIFT.Core.b2 /\
    giftDonaldsonRankOneCandidate.predictedB3 = GIFT.Core.b3 /\
    giftDonaldsonRankOneCandidate.twistedH1Dimension = 76 := by
  native_decide

/-- The Donaldson `b3` lock after the `S3` base contribution is removed. -/
def targetDonaldsonTwistedH1Dimension : Nat := GIFT.Core.b3 - 1

/-- Free-meridian approximation to the discriminant-link complement.

For a rank-one Picard-Lefschetz reflection on the rank-22 K3 cohomology local
system, a free group on `m` meridians contributes `m * 22`, modulo the single
combined rank-one image of `rho(g)-1`.  This is the optimistic no-relation
model for the twisted `H1` lock.
-/
structure DonaldsonTwistedH1FreeMeridianModel where
  meridianCount : Nat
  localSystemRank : Nat
  combinedMonodromyImageRank : Nat
  deriving DecidableEq, Repr

def DonaldsonTwistedH1FreeMeridianModel.freeTwistedH1Dimension
    (M : DonaldsonTwistedH1FreeMeridianModel) : Nat :=
  M.meridianCount * M.localSystemRank - M.combinedMonodromyImageRank

def rankOneReflectionFreeMeridianModel
    (meridianCount : Nat) : DonaldsonTwistedH1FreeMeridianModel where
  meridianCount := meridianCount
  localSystemRank := k3SecondCohomologyRank
  combinedMonodromyImageRank := 1

def rankOneReflectionFreeMeridianModels :
    List DonaldsonTwistedH1FreeMeridianModel :=
  [rankOneReflectionFreeMeridianModel 1,
   rankOneReflectionFreeMeridianModel 2,
   rankOneReflectionFreeMeridianModel 3,
   rankOneReflectionFreeMeridianModel 4,
   rankOneReflectionFreeMeridianModel 5,
   rankOneReflectionFreeMeridianModel 6,
   rankOneReflectionFreeMeridianModel 7,
   rankOneReflectionFreeMeridianModel 8]

def rankOneReflectionFreeMeridianDimensions : List Nat :=
  rankOneReflectionFreeMeridianModels.map
    (fun M => M.freeTwistedH1Dimension)

theorem rank_one_reflection_free_meridian_screen_misses_76 :
    targetDonaldsonTwistedH1Dimension = 76 /\
    rankOneReflectionFreeMeridianDimensions =
      [21, 43, 65, 87, 109, 131, 153, 175] /\
    rankOneReflectionFreeMeridianDimensions.contains
      targetDonaldsonTwistedH1Dimension = false := by
  native_decide

/-- Cell-rank bookkeeping for the first non-free Donaldson link model.

The rank-one free-meridian approximation jumps from `65` to `87`; hitting
`76` therefore requires a nontrivial twisted two-cell/relation map.  The first
possible closure is four meridians with relation rank `11`.
-/
structure DonaldsonTwistedH1RelationModel where
  meridianCount : Nat
  localSystemRank : Nat
  combinedMonodromyImageRank : Nat
  twoCellRelationRank : Nat
  linkComponentCountCertified : Bool
  relationRankCertified : Bool
  deriving DecidableEq, Repr

def DonaldsonTwistedH1RelationModel.freeDimension
    (M : DonaldsonTwistedH1RelationModel) : Nat :=
  M.meridianCount * M.localSystemRank - M.combinedMonodromyImageRank

def DonaldsonTwistedH1RelationModel.twistedH1Dimension
    (M : DonaldsonTwistedH1RelationModel) : Nat :=
  M.freeDimension - M.twoCellRelationRank

def DonaldsonTwistedH1RelationModel.predictedB3
    (M : DonaldsonTwistedH1RelationModel) : Nat :=
  1 + M.twistedH1Dimension

def minimalDonaldsonTwistedH1RelationModel :
    DonaldsonTwistedH1RelationModel where
  meridianCount := 4
  localSystemRank := k3SecondCohomologyRank
  combinedMonodromyImageRank := 1
  twoCellRelationRank := 11
  linkComponentCountCertified := false
  relationRankCertified := false

theorem minimal_donaldson_relation_model_closes_h1_algebraically :
    minimalDonaldsonTwistedH1RelationModel.freeDimension = 87 /\
    minimalDonaldsonTwistedH1RelationModel.twoCellRelationRank = 11 /\
    minimalDonaldsonTwistedH1RelationModel.twistedH1Dimension =
      targetDonaldsonTwistedH1Dimension /\
    minimalDonaldsonTwistedH1RelationModel.twistedH1Dimension = 76 /\
    minimalDonaldsonTwistedH1RelationModel.predictedB3 = GIFT.Core.b3 /\
    minimalDonaldsonTwistedH1RelationModel.linkComponentCountCertified = false /\
    minimalDonaldsonTwistedH1RelationModel.relationRankCertified = false := by
  native_decide

/-- Current status of the Donaldson `b3` lock.

The arithmetic obstruction is now localized: a free meridian complement cannot
hit `76`, while the first algebraic cell-rank model that does hit it requires a
rank-`11` twisted relation map in the discriminant-link complement.
-/
structure DonaldsonTwistedH1LockStatus where
  targetTwistedH1 : Nat
  freeMeridianScreenHitsTarget : Bool
  firstMeridianCountAboveTarget : Nat
  freeDimensionAtFirstAboveTarget : Nat
  requiredRelationRankAtFirstAboveTarget : Nat
  algebraicRelationModelHitsTarget : Bool
  linkRelationGeometryCertified : Bool
  deriving DecidableEq, Repr

def currentDonaldsonTwistedH1LockStatus :
    DonaldsonTwistedH1LockStatus where
  targetTwistedH1 := targetDonaldsonTwistedH1Dimension
  freeMeridianScreenHitsTarget := false
  firstMeridianCountAboveTarget := 4
  freeDimensionAtFirstAboveTarget := 87
  requiredRelationRankAtFirstAboveTarget := 11
  algebraicRelationModelHitsTarget := true
  linkRelationGeometryCertified := false

theorem current_donaldson_twisted_h1_lock_status_certificate :
    currentDonaldsonTwistedH1LockStatus.targetTwistedH1 = 76 /\
    currentDonaldsonTwistedH1LockStatus.freeMeridianScreenHitsTarget = false /\
    currentDonaldsonTwistedH1LockStatus.firstMeridianCountAboveTarget = 4 /\
    currentDonaldsonTwistedH1LockStatus.freeDimensionAtFirstAboveTarget = 87 /\
    currentDonaldsonTwistedH1LockStatus.requiredRelationRankAtFirstAboveTarget = 11 /\
    currentDonaldsonTwistedH1LockStatus.algebraicRelationModelHitsTarget = true /\
    currentDonaldsonTwistedH1LockStatus.linkRelationGeometryCertified = false := by
  native_decide

def rankOneDonaldsonFixedBlockRank : Nat := k3SecondCohomologyRank - 1
def rankOneDonaldsonMovedBlockRank : Nat := 1

/-- Rank of a relation map compatible with a single rank-one reflection.

Once the Donaldson monodromy is genuinely rank-one, the K3 cohomology local
system splits as a `21`-dimensional fixed block plus a `1`-dimensional moved
block.  Fox/Jacobian relation ranks are therefore not arbitrary: they have the
form `21*a + b`.
-/
def rankOneFoxRelationRank
    (fixedRelationMatrixRank movedRelationMatrixRank : Nat) : Nat :=
  rankOneDonaldsonFixedBlockRank * fixedRelationMatrixRank +
    rankOneDonaldsonMovedBlockRank * movedRelationMatrixRank

def rankOneFoxRelationRanksForMeridianCount (meridianCount : Nat) : List Nat :=
  (List.range (meridianCount + 1)).flatMap
    (fun fixedRank =>
      (List.range (meridianCount + 1)).map
        (fun movedRank => rankOneFoxRelationRank fixedRank movedRank))

theorem rank_one_fox_four_meridian_ranks_reject_naive_rank_11 :
    (rankOneFoxRelationRanksForMeridianCount 4).contains 11 = false := by
  native_decide

/-- A block-compatible relation profile for the rank-one Donaldson local system. -/
structure DonaldsonRankOneFoxRelationProfile where
  meridianCount : Nat
  fixedBlockRank : Nat
  movedBlockRank : Nat
  d0Rank : Nat
  fixedRelationMatrixRank : Nat
  movedRelationMatrixRank : Nat
  deriving DecidableEq, Repr

def DonaldsonRankOneFoxRelationProfile.localSystemRank
    (P : DonaldsonRankOneFoxRelationProfile) : Nat :=
  P.fixedBlockRank + P.movedBlockRank

def DonaldsonRankOneFoxRelationProfile.relationRank
    (P : DonaldsonRankOneFoxRelationProfile) : Nat :=
  P.fixedBlockRank * P.fixedRelationMatrixRank +
    P.movedBlockRank * P.movedRelationMatrixRank

def DonaldsonRankOneFoxRelationProfile.twistedH1Dimension
    (P : DonaldsonRankOneFoxRelationProfile) : Nat :=
  P.meridianCount * P.localSystemRank - P.d0Rank - P.relationRank

def DonaldsonRankOneFoxRelationProfile.predictedB3
    (P : DonaldsonRankOneFoxRelationProfile) : Nat :=
  1 + P.twistedH1Dimension

def rankOneFoxRelationProfile
    (meridianCount fixedRelationMatrixRank movedRelationMatrixRank : Nat) :
    DonaldsonRankOneFoxRelationProfile where
  meridianCount := meridianCount
  fixedBlockRank := rankOneDonaldsonFixedBlockRank
  movedBlockRank := rankOneDonaldsonMovedBlockRank
  d0Rank := 1
  fixedRelationMatrixRank := fixedRelationMatrixRank
  movedRelationMatrixRank := movedRelationMatrixRank

def rankOneFoxTargetProfilesBelow14 :
    List DonaldsonRankOneFoxRelationProfile :=
  (List.range 13).flatMap
    (fun index =>
      let meridianCount := index + 1
      (List.range (meridianCount + 1)).flatMap
        (fun fixedRank =>
          (List.range (meridianCount + 1)).filterMap
            (fun movedRank =>
              let P := rankOneFoxRelationProfile meridianCount fixedRank movedRank
              if P.twistedH1Dimension == targetDonaldsonTwistedH1Dimension then
                some P
              else
                none)))

def rankOneFoxTargetProfilesUpTo20 :
    List DonaldsonRankOneFoxRelationProfile :=
  (List.range 20).flatMap
    (fun index =>
      let meridianCount := index + 1
      (List.range (meridianCount + 1)).flatMap
        (fun fixedRank =>
          (List.range (meridianCount + 1)).filterMap
            (fun movedRank =>
              let P := rankOneFoxRelationProfile meridianCount fixedRank movedRank
              if P.twistedH1Dimension == targetDonaldsonTwistedH1Dimension then
                some P
              else
                none)))

def minimalRankOneFoxTargetProfile : DonaldsonRankOneFoxRelationProfile :=
  rankOneFoxRelationProfile 14 11 0

theorem rank_one_fox_relation_profiles_force_at_least_14_meridians :
    rankOneFoxTargetProfilesBelow14 = [] /\
    rankOneFoxTargetProfilesUpTo20.head? = some minimalRankOneFoxTargetProfile /\
    rankOneFoxTargetProfilesUpTo20.length = 7 /\
    minimalRankOneFoxTargetProfile.relationRank = 231 /\
    minimalRankOneFoxTargetProfile.twistedH1Dimension =
      targetDonaldsonTwistedH1Dimension /\
    minimalRankOneFoxTargetProfile.predictedB3 = GIFT.Core.b3 := by
  native_decide

/-- Stronger lock status after imposing the rank-one Fox block structure. -/
structure DonaldsonRankOneFoxLockStatus where
  naiveFourMeridianRelationRankNeeded : Nat
  naiveFourMeridianRankCompatibleWithRankOneFox : Bool
  minimumMeridianCountForTargetUpTo20 : Nat
  fixedRelationRankAtMinimum : Nat
  movedRelationRankAtMinimum : Nat
  relationRankAtMinimum : Nat
  twistedH1AtMinimum : Nat
  rankOneFoxGeometryCertified : Bool
  deriving DecidableEq, Repr

def currentDonaldsonRankOneFoxLockStatus :
    DonaldsonRankOneFoxLockStatus where
  naiveFourMeridianRelationRankNeeded := 11
  naiveFourMeridianRankCompatibleWithRankOneFox := false
  minimumMeridianCountForTargetUpTo20 := 14
  fixedRelationRankAtMinimum := 11
  movedRelationRankAtMinimum := 0
  relationRankAtMinimum := 231
  twistedH1AtMinimum := targetDonaldsonTwistedH1Dimension
  rankOneFoxGeometryCertified := false

theorem current_donaldson_rank_one_fox_lock_status_certificate :
    currentDonaldsonRankOneFoxLockStatus.naiveFourMeridianRelationRankNeeded = 11 /\
    currentDonaldsonRankOneFoxLockStatus.naiveFourMeridianRankCompatibleWithRankOneFox = false /\
    currentDonaldsonRankOneFoxLockStatus.minimumMeridianCountForTargetUpTo20 = 14 /\
    currentDonaldsonRankOneFoxLockStatus.fixedRelationRankAtMinimum = 11 /\
    currentDonaldsonRankOneFoxLockStatus.movedRelationRankAtMinimum = 0 /\
    currentDonaldsonRankOneFoxLockStatus.relationRankAtMinimum = 231 /\
    currentDonaldsonRankOneFoxLockStatus.twistedH1AtMinimum = 76 /\
    currentDonaldsonRankOneFoxLockStatus.rankOneFoxGeometryCertified = false := by
  native_decide

/-- The first Fox-compatible profile reinterpreted through existing GIFT geometry.

The codebase already carries the two numbers required by the rank-one Fox
screen:

* `14 = dim(G2) = 2 * dim(K7) = 2 * |Fano lines|`;
* `11 = D_bulk`, and `b3 = dim(K7) * D_bulk`.

This is not yet a constructed discriminant link.  It is a concrete internal
geometric target: a Donaldson discriminant whose meridians are indexed by the
G2/Fano double-incidence geometry and whose fixed-block relation rank is the
M-theory bulk dimension.
-/
def giftInternalDonaldsonFoxProfile : DonaldsonRankOneFoxRelationProfile :=
  rankOneFoxRelationProfile GIFT.Core.dim_G2 GIFT.Core.D_bulk 0

structure DonaldsonGIFTInternalGeometryCandidate where
  profile : DonaldsonRankOneFoxRelationProfile
  meridiansFromG2Adjoint : Bool
  meridiansFromFanoDoubleIncidence : Bool
  fixedRelationsFromBulkDimension : Bool
  b3FactorizationFromK7Bulk : Bool
  globalDiscriminantLinkCertified : Bool
  deriving DecidableEq, Repr

def currentDonaldsonGIFTInternalGeometryCandidate :
    DonaldsonGIFTInternalGeometryCandidate where
  profile := giftInternalDonaldsonFoxProfile
  meridiansFromG2Adjoint := true
  meridiansFromFanoDoubleIncidence := true
  fixedRelationsFromBulkDimension := true
  b3FactorizationFromK7Bulk := true
  globalDiscriminantLinkCertified := false

theorem gift_internal_donaldson_fox_profile_closes_b3 :
    giftInternalDonaldsonFoxProfile.meridianCount = GIFT.Core.dim_G2 /\
    giftInternalDonaldsonFoxProfile.meridianCount = 14 /\
    giftInternalDonaldsonFoxProfile.meridianCount =
      2 * GIFT.Foundations.G2CrossProduct.fano_lines.length /\
    giftInternalDonaldsonFoxProfile.fixedRelationMatrixRank =
      GIFT.Core.D_bulk /\
    giftInternalDonaldsonFoxProfile.fixedRelationMatrixRank = 11 /\
    giftInternalDonaldsonFoxProfile.movedRelationMatrixRank = 0 /\
    rankOneDonaldsonFixedBlockRank = GIFT.Core.b2 /\
    giftInternalDonaldsonFoxProfile.relationRank =
      GIFT.Core.b2 * GIFT.Core.D_bulk /\
    giftInternalDonaldsonFoxProfile.relationRank = 231 /\
    giftInternalDonaldsonFoxProfile.twistedH1Dimension =
      targetDonaldsonTwistedH1Dimension /\
    giftInternalDonaldsonFoxProfile.predictedB3 = GIFT.Core.b3 /\
    GIFT.Core.dim_G2 = 2 * GIFT.Core.dim_K7 /\
    GIFT.Core.b3 = GIFT.Core.dim_K7 * GIFT.Core.D_bulk := by
  native_decide

theorem current_donaldson_gift_internal_geometry_candidate_certificate :
    currentDonaldsonGIFTInternalGeometryCandidate.profile =
      giftInternalDonaldsonFoxProfile /\
    currentDonaldsonGIFTInternalGeometryCandidate.meridiansFromG2Adjoint = true /\
    currentDonaldsonGIFTInternalGeometryCandidate.meridiansFromFanoDoubleIncidence = true /\
    currentDonaldsonGIFTInternalGeometryCandidate.fixedRelationsFromBulkDimension = true /\
    currentDonaldsonGIFTInternalGeometryCandidate.b3FactorizationFromK7Bulk = true /\
    currentDonaldsonGIFTInternalGeometryCandidate.globalDiscriminantLinkCertified = false /\
    currentDonaldsonGIFTInternalGeometryCandidate.profile.twistedH1Dimension = 76 /\
    currentDonaldsonGIFTInternalGeometryCandidate.profile.predictedB3 =
      GIFT.Core.b3 := by
  native_decide

/-- Explicit Fano-oriented meridian relation model.

The 14 meridians are the 7 Fano lines doubled by orientation.  The fixed-block
relation matrix is audited externally by
`scripts/donaldson_fano_link_model.py`:

* 7 orientation-pair relations;
* 4 projective-coordinate Fano relations;
* combined rank `11 = D_bulk`;
* fixed quotient rank `3 = N_gen`.

The moved block has no relation rows; after the rank-one monodromy `d0` image,
it contributes `14 - 1 = 13 = alpha_sum`.
-/
structure DonaldsonFanoOrientedMeridianLinkModel where
  fanoLineCount : Nat
  orientedMeridianCount : Nat
  orientationPairRelationRank : Nat
  fanoProjectiveCoordinateRelationRank : Nat
  fixedRelationMatrixRank : Nat
  fixedQuotientRank : Nat
  movedRelationMatrixRank : Nat
  movedQuotientRank : Nat
  relationMatrixRankAudited : Bool
  actualDonaldsonDiscriminantLinkCertified : Bool
  deriving DecidableEq, Repr

def DonaldsonFanoOrientedMeridianLinkModel.fixedRelationRankFromRows
    (M : DonaldsonFanoOrientedMeridianLinkModel) : Nat :=
  M.orientationPairRelationRank + M.fanoProjectiveCoordinateRelationRank

def DonaldsonFanoOrientedMeridianLinkModel.fixedQuotientRankFromRows
    (M : DonaldsonFanoOrientedMeridianLinkModel) : Nat :=
  M.orientedMeridianCount - M.fixedRelationRankFromRows

def DonaldsonFanoOrientedMeridianLinkModel.movedQuotientRankFromRows
    (M : DonaldsonFanoOrientedMeridianLinkModel) : Nat :=
  M.orientedMeridianCount - 1 - M.movedRelationMatrixRank

def DonaldsonFanoOrientedMeridianLinkModel.twistedH1Dimension
    (M : DonaldsonFanoOrientedMeridianLinkModel) : Nat :=
  rankOneDonaldsonFixedBlockRank * M.fixedQuotientRank +
    rankOneDonaldsonMovedBlockRank * M.movedQuotientRank

def DonaldsonFanoOrientedMeridianLinkModel.predictedB3
    (M : DonaldsonFanoOrientedMeridianLinkModel) : Nat :=
  1 + M.twistedH1Dimension

def currentDonaldsonFanoOrientedMeridianLinkModel :
    DonaldsonFanoOrientedMeridianLinkModel where
  fanoLineCount := GIFT.Foundations.G2CrossProduct.fano_lines.length
  orientedMeridianCount := 2 * GIFT.Foundations.G2CrossProduct.fano_lines.length
  orientationPairRelationRank := GIFT.Foundations.G2CrossProduct.fano_lines.length
  fanoProjectiveCoordinateRelationRank := 4
  fixedRelationMatrixRank := GIFT.Core.D_bulk
  fixedQuotientRank := GIFT.Core.N_gen
  movedRelationMatrixRank := 0
  movedQuotientRank := GIFT.Core.alpha_sum
  relationMatrixRankAudited := true
  actualDonaldsonDiscriminantLinkCertified := false

theorem current_donaldson_fano_oriented_link_model_certificate :
    currentDonaldsonFanoOrientedMeridianLinkModel.fanoLineCount = 7 /\
    currentDonaldsonFanoOrientedMeridianLinkModel.orientedMeridianCount =
      GIFT.Core.dim_G2 /\
    currentDonaldsonFanoOrientedMeridianLinkModel.orientedMeridianCount = 14 /\
    currentDonaldsonFanoOrientedMeridianLinkModel.orientationPairRelationRank = 7 /\
    currentDonaldsonFanoOrientedMeridianLinkModel.fanoProjectiveCoordinateRelationRank = 4 /\
    currentDonaldsonFanoOrientedMeridianLinkModel.fixedRelationRankFromRows =
      GIFT.Core.D_bulk /\
    currentDonaldsonFanoOrientedMeridianLinkModel.fixedRelationMatrixRank =
      currentDonaldsonFanoOrientedMeridianLinkModel.fixedRelationRankFromRows /\
    currentDonaldsonFanoOrientedMeridianLinkModel.fixedRelationMatrixRank = 11 /\
    currentDonaldsonFanoOrientedMeridianLinkModel.fixedQuotientRankFromRows =
      GIFT.Core.N_gen /\
    currentDonaldsonFanoOrientedMeridianLinkModel.fixedQuotientRank =
      GIFT.Core.N_gen /\
    currentDonaldsonFanoOrientedMeridianLinkModel.movedRelationMatrixRank = 0 /\
    currentDonaldsonFanoOrientedMeridianLinkModel.movedQuotientRankFromRows =
      GIFT.Core.alpha_sum /\
    currentDonaldsonFanoOrientedMeridianLinkModel.movedQuotientRank =
      GIFT.Core.alpha_sum /\
    currentDonaldsonFanoOrientedMeridianLinkModel.twistedH1Dimension =
      targetDonaldsonTwistedH1Dimension /\
    currentDonaldsonFanoOrientedMeridianLinkModel.twistedH1Dimension = 76 /\
    currentDonaldsonFanoOrientedMeridianLinkModel.predictedB3 = GIFT.Core.b3 /\
    currentDonaldsonFanoOrientedMeridianLinkModel.relationMatrixRankAudited = true /\
    currentDonaldsonFanoOrientedMeridianLinkModel.actualDonaldsonDiscriminantLinkCertified = false := by
  native_decide

theorem fano_oriented_link_model_realizes_internal_fox_profile :
    rankOneFoxRelationProfile
      currentDonaldsonFanoOrientedMeridianLinkModel.orientedMeridianCount
      currentDonaldsonFanoOrientedMeridianLinkModel.fixedRelationMatrixRank
      currentDonaldsonFanoOrientedMeridianLinkModel.movedRelationMatrixRank =
        giftInternalDonaldsonFoxProfile /\
    currentDonaldsonFanoOrientedMeridianLinkModel.twistedH1Dimension =
      giftInternalDonaldsonFoxProfile.twistedH1Dimension /\
    currentDonaldsonFanoOrientedMeridianLinkModel.predictedB3 =
      giftInternalDonaldsonFoxProfile.predictedB3 := by
  native_decide

/-- Integral cokernel audit for the Fano-oriented relation matrix.

The rank over `Q` is not enough for a link complement model: a link
abelianization should be torsion-free.  The companion script computes all
maximal minors of the `11 x 14` integer relation matrix.  Their gcd is `1`,
so the integer cokernel has no torsion and rank `3`.
-/
structure DonaldsonFanoIntegralCokernelAudit where
  relationMatrixRows : Nat
  relationMatrixColumns : Nat
  rationalRank : Nat
  nonzeroMaximalMinorCount : Nat
  maximalMinorGCD : Nat
  maxAbsMaximalMinor : Nat
  integralCokernelRank : Nat
  integralCokernelTorsionFree : Bool
  compatibleWithThreeComponentLinkAbelianization : Bool
  actualWirtingerPresentationCertified : Bool
  deriving DecidableEq, Repr

def currentDonaldsonFanoIntegralCokernelAudit :
    DonaldsonFanoIntegralCokernelAudit where
  relationMatrixRows := 11
  relationMatrixColumns := GIFT.Core.dim_G2
  rationalRank := 11
  nonzeroMaximalMinorCount := 232
  maximalMinorGCD := 1
  maxAbsMaximalMinor := 2
  integralCokernelRank := GIFT.Core.N_gen
  integralCokernelTorsionFree := true
  compatibleWithThreeComponentLinkAbelianization := true
  actualWirtingerPresentationCertified := false

theorem current_donaldson_fano_integral_cokernel_audit_certificate :
    currentDonaldsonFanoIntegralCokernelAudit.relationMatrixRows = 11 /\
    currentDonaldsonFanoIntegralCokernelAudit.relationMatrixColumns =
      GIFT.Core.dim_G2 /\
    currentDonaldsonFanoIntegralCokernelAudit.rationalRank =
      GIFT.Core.D_bulk /\
    currentDonaldsonFanoIntegralCokernelAudit.nonzeroMaximalMinorCount = 232 /\
    currentDonaldsonFanoIntegralCokernelAudit.maximalMinorGCD = 1 /\
    currentDonaldsonFanoIntegralCokernelAudit.maxAbsMaximalMinor = 2 /\
    currentDonaldsonFanoIntegralCokernelAudit.integralCokernelRank =
      GIFT.Core.N_gen /\
    currentDonaldsonFanoIntegralCokernelAudit.integralCokernelTorsionFree = true /\
    currentDonaldsonFanoIntegralCokernelAudit.compatibleWithThreeComponentLinkAbelianization = true /\
    currentDonaldsonFanoIntegralCokernelAudit.actualWirtingerPresentationCertified = false := by
  native_decide

/-- Quotient-image audit for the Fano relation matrix.

Using the unimodular minor on columns `0..10`, columns `11,12,13` give an
integral `Z^3` quotient basis.  In that basis the 14 oriented meridians collapse
to seven distinct integral directions, and those seven directions reduce modulo
`2` to the seven nonzero points of `F2^3`, i.e. the Fano plane.
-/
structure DonaldsonFanoQuotientImageAudit where
  quotientRank : Nat
  unitMinorPivotColumnCount : Nat
  freeQuotientColumnCount : Nat
  quotientImageDirectionCount : Nat
  orientationPairsShareQuotientImages : Bool
  modTwoNonzeroFanoPointCount : Nat
  modTwoFanoPlaneComplete : Bool
  meridianMapToActualLinkComponentsCertified : Bool
  deriving DecidableEq, Repr

def currentDonaldsonFanoQuotientImageAudit :
    DonaldsonFanoQuotientImageAudit where
  quotientRank := GIFT.Core.N_gen
  unitMinorPivotColumnCount := 11
  freeQuotientColumnCount := GIFT.Core.N_gen
  quotientImageDirectionCount := GIFT.Foundations.G2CrossProduct.fano_lines.length
  orientationPairsShareQuotientImages := true
  modTwoNonzeroFanoPointCount := GIFT.Foundations.G2CrossProduct.fano_lines.length
  modTwoFanoPlaneComplete := true
  meridianMapToActualLinkComponentsCertified := false

theorem current_donaldson_fano_quotient_image_audit_certificate :
    currentDonaldsonFanoQuotientImageAudit.quotientRank = GIFT.Core.N_gen /\
    currentDonaldsonFanoQuotientImageAudit.unitMinorPivotColumnCount =
      GIFT.Core.D_bulk /\
    currentDonaldsonFanoQuotientImageAudit.freeQuotientColumnCount =
      GIFT.Core.N_gen /\
    currentDonaldsonFanoQuotientImageAudit.quotientImageDirectionCount = 7 /\
    currentDonaldsonFanoQuotientImageAudit.orientationPairsShareQuotientImages = true /\
    currentDonaldsonFanoQuotientImageAudit.modTwoNonzeroFanoPointCount = 7 /\
    currentDonaldsonFanoQuotientImageAudit.modTwoFanoPlaneComplete = true /\
    currentDonaldsonFanoQuotientImageAudit.meridianMapToActualLinkComponentsCertified = false := by
  native_decide

/-- Group-presentation screen for the Fano Donaldson link candidate.

The relator presentation has the correct link-like deficiency and integral
abelianization, but it is not yet a Wirtinger presentation because the four
projective-coordinate relators are multi-meridian words.
-/
structure DonaldsonFanoGroupPresentationAudit where
  generatorCount : Nat
  relatorCount : Nat
  orientationRelatorCount : Nat
  projectiveCoordinateRelatorCount : Nat
  deficiency : Nat
  projectiveRelatorLengths : List Nat
  exponentMatrixRank : Nat
  abelianizationRank : Nat
  integralCokernelTorsionFree : Bool
  modTwoFanoPlaneComplete : Bool
  directWirtingerLengthScreen : Bool
  wirtingerPresentationCertified : Bool
  deriving DecidableEq, Repr

def currentDonaldsonFanoGroupPresentationAudit :
    DonaldsonFanoGroupPresentationAudit where
  generatorCount := GIFT.Core.dim_G2
  relatorCount := GIFT.Core.D_bulk
  orientationRelatorCount := GIFT.Foundations.G2CrossProduct.fano_lines.length
  projectiveCoordinateRelatorCount := 4
  deficiency := GIFT.Core.N_gen
  projectiveRelatorLengths := [7, 4, 4, 4]
  exponentMatrixRank := GIFT.Core.D_bulk
  abelianizationRank := GIFT.Core.N_gen
  integralCokernelTorsionFree := true
  modTwoFanoPlaneComplete := true
  directWirtingerLengthScreen := false
  wirtingerPresentationCertified := false

theorem current_donaldson_fano_group_presentation_audit_certificate :
    currentDonaldsonFanoGroupPresentationAudit.generatorCount =
      GIFT.Core.dim_G2 /\
    currentDonaldsonFanoGroupPresentationAudit.generatorCount = 14 /\
    currentDonaldsonFanoGroupPresentationAudit.relatorCount =
      GIFT.Core.D_bulk /\
    currentDonaldsonFanoGroupPresentationAudit.orientationRelatorCount = 7 /\
    currentDonaldsonFanoGroupPresentationAudit.projectiveCoordinateRelatorCount = 4 /\
    currentDonaldsonFanoGroupPresentationAudit.deficiency =
      GIFT.Core.N_gen /\
    currentDonaldsonFanoGroupPresentationAudit.projectiveRelatorLengths =
      [7, 4, 4, 4] /\
    currentDonaldsonFanoGroupPresentationAudit.exponentMatrixRank =
      GIFT.Core.D_bulk /\
    currentDonaldsonFanoGroupPresentationAudit.abelianizationRank =
      GIFT.Core.N_gen /\
    currentDonaldsonFanoGroupPresentationAudit.integralCokernelTorsionFree = true /\
    currentDonaldsonFanoGroupPresentationAudit.modTwoFanoPlaneComplete = true /\
    currentDonaldsonFanoGroupPresentationAudit.directWirtingerLengthScreen = false /\
    currentDonaldsonFanoGroupPresentationAudit.wirtingerPresentationCertified = false := by
  native_decide

/-- Short-relator Tietze expansion of the Fano presentation.

The four long projective relators can be expanded into length-`<=3` relators
by adding prefix generators.  This preserves deficiency and integral
abelianization.  It is still not an ordinary Wirtinger presentation: the rows
do not all have zero exponent sum, and the original meridians have seven Fano
directions rather than three component-meridian classes.
-/
structure DonaldsonFanoTietzeExpansionAudit where
  originalGeneratorCount : Nat
  originalRelatorCount : Nat
  originalDeficiency : Nat
  auxiliaryGeneratorCount : Nat
  expandedGeneratorCount : Nat
  expandedRelatorCount : Nat
  expandedDeficiency : Nat
  expandedMaxRelatorLength : Nat
  expandedRelatorsLengthAtMostThree : Bool
  expandedExponentMatrixRank : Nat
  nonzeroMaximalMinorCount : Nat
  maximalMinorGCD : Nat
  abelianizationRank : Nat
  integralCokernelTorsionFree : Bool
  deficiencyPreserved : Bool
  zeroExponentSumRows : Nat
  allRowsZeroExponentSum : Bool
  originalMeridianDirectionCount : Nat
  ordinaryThreeComponentWirtingerMeridianScreen : Bool
  tietzeShortRelatorExpansionCertified : Bool
  wirtingerConjugationPresentationCertified : Bool
  deriving DecidableEq, Repr

def currentDonaldsonFanoTietzeExpansionAudit :
    DonaldsonFanoTietzeExpansionAudit where
  originalGeneratorCount := GIFT.Core.dim_G2
  originalRelatorCount := GIFT.Core.D_bulk
  originalDeficiency := GIFT.Core.N_gen
  auxiliaryGeneratorCount := 11
  expandedGeneratorCount := 25
  expandedRelatorCount := 22
  expandedDeficiency := GIFT.Core.N_gen
  expandedMaxRelatorLength := 3
  expandedRelatorsLengthAtMostThree := true
  expandedExponentMatrixRank := 22
  nonzeroMaximalMinorCount := 1055
  maximalMinorGCD := 1
  abelianizationRank := GIFT.Core.N_gen
  integralCokernelTorsionFree := true
  deficiencyPreserved := true
  zeroExponentSumRows := 7
  allRowsZeroExponentSum := false
  originalMeridianDirectionCount := 7
  ordinaryThreeComponentWirtingerMeridianScreen := false
  tietzeShortRelatorExpansionCertified := true
  wirtingerConjugationPresentationCertified := false

theorem current_donaldson_fano_tietze_expansion_audit_certificate :
    currentDonaldsonFanoTietzeExpansionAudit.originalGeneratorCount =
      GIFT.Core.dim_G2 /\
    currentDonaldsonFanoTietzeExpansionAudit.originalRelatorCount =
      GIFT.Core.D_bulk /\
    currentDonaldsonFanoTietzeExpansionAudit.originalDeficiency =
      GIFT.Core.N_gen /\
    currentDonaldsonFanoTietzeExpansionAudit.auxiliaryGeneratorCount = 11 /\
    currentDonaldsonFanoTietzeExpansionAudit.expandedGeneratorCount = 25 /\
    currentDonaldsonFanoTietzeExpansionAudit.expandedRelatorCount = 22 /\
    currentDonaldsonFanoTietzeExpansionAudit.expandedDeficiency =
      GIFT.Core.N_gen /\
    currentDonaldsonFanoTietzeExpansionAudit.expandedMaxRelatorLength = 3 /\
    currentDonaldsonFanoTietzeExpansionAudit.expandedRelatorsLengthAtMostThree = true /\
    currentDonaldsonFanoTietzeExpansionAudit.expandedExponentMatrixRank = 22 /\
    currentDonaldsonFanoTietzeExpansionAudit.nonzeroMaximalMinorCount = 1055 /\
    currentDonaldsonFanoTietzeExpansionAudit.maximalMinorGCD = 1 /\
    currentDonaldsonFanoTietzeExpansionAudit.abelianizationRank =
      GIFT.Core.N_gen /\
    currentDonaldsonFanoTietzeExpansionAudit.integralCokernelTorsionFree = true /\
    currentDonaldsonFanoTietzeExpansionAudit.deficiencyPreserved = true /\
    currentDonaldsonFanoTietzeExpansionAudit.zeroExponentSumRows = 7 /\
    currentDonaldsonFanoTietzeExpansionAudit.allRowsZeroExponentSum = false /\
    currentDonaldsonFanoTietzeExpansionAudit.originalMeridianDirectionCount = 7 /\
    currentDonaldsonFanoTietzeExpansionAudit.ordinaryThreeComponentWirtingerMeridianScreen = false /\
    currentDonaldsonFanoTietzeExpansionAudit.tietzeShortRelatorExpansionCertified = true /\
    currentDonaldsonFanoTietzeExpansionAudit.wirtingerConjugationPresentationCertified = false := by
  native_decide

/-- Explicit monodromy reflection ledger for the Donaldson route.

The useful point is that `b2=21` comes from invariant cohomology in the full
K3 `H2`, not from a projective Picard-rank intersection as in standard XTCS.
-/
structure DonaldsonMonodromyReflectionLedger where
  totalH2Rank : Nat
  picardInvariantRank : Nat
  transcendentalRank : Nat
  movedRank : Nat
  invariantRank : Nat
  vanishingClassSquare : Int
  globalTorelliScreen : Bool
  lefschetzScreen : Bool
  deriving DecidableEq, Repr

def currentDonaldsonMonodromyReflectionLedger :
    DonaldsonMonodromyReflectionLedger where
  totalH2Rank := k3SecondCohomologyRank
  picardInvariantRank := ci222K3PicardRank
  transcendentalRank := ci222K3TranscendentalRank
  movedRank := 1
  invariantRank := 21
  vanishingClassSquare := -2
  globalTorelliScreen := true
  lefschetzScreen := true

theorem current_donaldson_monodromy_reflection_certificate :
    currentDonaldsonMonodromyReflectionLedger.totalH2Rank = 22 /\
    currentDonaldsonMonodromyReflectionLedger.picardInvariantRank = 1 /\
    currentDonaldsonMonodromyReflectionLedger.transcendentalRank = 21 /\
    currentDonaldsonMonodromyReflectionLedger.movedRank = 1 /\
    currentDonaldsonMonodromyReflectionLedger.invariantRank = GIFT.Core.b2 /\
    currentDonaldsonMonodromyReflectionLedger.vanishingClassSquare = -2 /\
    currentDonaldsonMonodromyReflectionLedger.globalTorelliScreen = true /\
    currentDonaldsonMonodromyReflectionLedger.lefschetzScreen = true := by
  native_decide

/-- Spectral evidence for the Donaldson/K3 adiabatic interpretation.

These are rounded readings of the local spectral JSON artefacts.  They support
the adiabatic model but do not prove an exact compact torsion-free G2
construction.
-/
structure DonaldsonSpectralAdiabaticEvidence where
  lambda1Micro : Nat
  lambda1RichardsonErrorMicro : Nat
  effectiveDimensionMilli : Nat
  expectedDimensionMilli : Nat
  poissonChi2Milli : Nat
  goeChi2Milli : Nat
  distinctEnergyLevelsBelow20 : Nat
  statesWithMultiplicityBelow20 : Nat
  spectralJsonAudited : Bool
  supportsAdiabaticInterpretation : Bool
  provesTorsionFreeMetric : Bool
  deriving DecidableEq, Repr

def DonaldsonSpectralAdiabaticEvidence.dimensionClose
    (E : DonaldsonSpectralAdiabaticEvidence) : Bool :=
  decide (E.effectiveDimensionMilli + 100 >= E.expectedDimensionMilli /\
    E.effectiveDimensionMilli <= E.expectedDimensionMilli + 100)

def DonaldsonSpectralAdiabaticEvidence.poissonBeatsGOE
    (E : DonaldsonSpectralAdiabaticEvidence) : Bool :=
  decide (E.poissonChi2Milli < E.goeChi2Milli)

def currentDonaldsonSpectralAdiabaticEvidence :
    DonaldsonSpectralAdiabaticEvidence where
  lambda1Micro := 124607
  lambda1RichardsonErrorMicro := 156
  effectiveDimensionMilli := 6920
  expectedDimensionMilli := 7000
  poissonChi2Milli := 1358
  goeChi2Milli := 28034
  distinctEnergyLevelsBelow20 := 22671
  statesWithMultiplicityBelow20 := 210060
  spectralJsonAudited := true
  supportsAdiabaticInterpretation := true
  provesTorsionFreeMetric := false

theorem current_donaldson_spectral_adiabatic_evidence_certificate :
    currentDonaldsonSpectralAdiabaticEvidence.lambda1Micro = 124607 /\
    currentDonaldsonSpectralAdiabaticEvidence.lambda1RichardsonErrorMicro < 200 /\
    currentDonaldsonSpectralAdiabaticEvidence.dimensionClose = true /\
    currentDonaldsonSpectralAdiabaticEvidence.poissonBeatsGOE = true /\
    currentDonaldsonSpectralAdiabaticEvidence.distinctEnergyLevelsBelow20 = 22671 /\
    currentDonaldsonSpectralAdiabaticEvidence.statesWithMultiplicityBelow20 = 210060 /\
    currentDonaldsonSpectralAdiabaticEvidence.supportsAdiabaticInterpretation = true /\
    currentDonaldsonSpectralAdiabaticEvidence.provesTorsionFreeMetric = false := by
  native_decide

def DonaldsonK3Fibration.geometricallyCertified
    (D : DonaldsonK3Fibration) : Prop :=
  D.picardRankCertified = true /\
  D.monodromyCertified = true /\
  D.linkComplementCertified = true /\
  D.torsionFreeG2FibrationCertified = true

theorem gift_donaldson_candidate_not_yet_geometrically_certified :
    giftDonaldsonRankOneCandidate.geometricallyCertified -> False := by
  intro h
  simp [DonaldsonK3Fibration.geometricallyCertified,
    giftDonaldsonRankOneCandidate] at h

theorem donaldson_route_certificate :
    giftDonaldsonRankOneCandidate.predictedB2 = GIFT.Core.b2 /\
    giftDonaldsonRankOneCandidate.predictedB3 = GIFT.Core.b3 /\
    giftDonaldsonRankOneCandidate.picardRankCertified = true /\
    giftDonaldsonRankOneCandidate.monodromyCertified = true /\
    giftDonaldsonRankOneCandidate.linkComplementCertified = false /\
    giftDonaldsonRankOneCandidate.torsionFreeG2FibrationCertified = false /\
    (giftDonaldsonRankOneCandidate.geometricallyCertified -> False) := by
  exact And.intro (by native_decide)
    (And.intro (by native_decide)
    (And.intro (by native_decide)
    (And.intro (by native_decide)
    (And.intro (by native_decide)
    (And.intro (by native_decide)
      gift_donaldson_candidate_not_yet_geometrically_certified)))))

/-- Consolidated strategy status after the broader-picture audit.

The Donaldson route is the primary surviving geometric route.  It has a closed
`b2` mechanism and strong spectral support, but still lacks the singular-link
cohomology and torsion-free global construction data needed for a completed
manifold theorem.
-/
structure LaFourniereClaudeDonaldsonStrategyStatus where
  joyceOrbifoldClassicFalsified : Bool
  orthogonalTCSFalsified : Bool
  standardXTCSFalsified : Bool
  regularCCY7Falsified : Bool
  donaldsonB2Closed : Bool
  donaldsonB3LinkLockClosed : Bool
  jkLensPublishedSupport : Bool
  spectralAdiabaticEvidence : Bool
  torsionFreeGlobalConstructionCertified : Bool
  deriving DecidableEq, Repr

def currentLaFourniereClaudeDonaldsonStrategyStatus :
    LaFourniereClaudeDonaldsonStrategyStatus where
  joyceOrbifoldClassicFalsified := true
  orthogonalTCSFalsified := true
  standardXTCSFalsified := true
  regularCCY7Falsified := true
  donaldsonB2Closed := true
  donaldsonB3LinkLockClosed := false
  jkLensPublishedSupport := false
  spectralAdiabaticEvidence := true
  torsionFreeGlobalConstructionCertified := false

theorem current_la_fourniere_claude_donaldson_strategy_certificate :
    currentLaFourniereClaudeDonaldsonStrategyStatus.joyceOrbifoldClassicFalsified = true /\
    currentLaFourniereClaudeDonaldsonStrategyStatus.orthogonalTCSFalsified = true /\
    currentLaFourniereClaudeDonaldsonStrategyStatus.standardXTCSFalsified = true /\
    currentLaFourniereClaudeDonaldsonStrategyStatus.regularCCY7Falsified = true /\
    currentLaFourniereClaudeDonaldsonStrategyStatus.donaldsonB2Closed = true /\
    currentLaFourniereClaudeDonaldsonStrategyStatus.donaldsonB3LinkLockClosed = false /\
    currentLaFourniereClaudeDonaldsonStrategyStatus.jkLensPublishedSupport = false /\
    currentLaFourniereClaudeDonaldsonStrategyStatus.spectralAdiabaticEvidence = true /\
    currentLaFourniereClaudeDonaldsonStrategyStatus.torsionFreeGlobalConstructionCertified = false := by
  native_decide

end GIFT.Foundations.DonaldsonCoassociativeFibration
