#!/usr/bin/env python3
"""Keep the audit's import closure equal to the complete library source tree."""
from pathlib import Path
import argparse
ROOT = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser()
p.add_argument('--check', action='store_true')
args = p.parse_args()
text = '-- Generated by scripts/update_verification_imports.py.\n' + ''.join(
    'import ' + str(f.relative_to(ROOT).with_suffix('')).replace('/', '.') + '\n'
    for f in sorted((ROOT/'GIFT').rglob('*.lean')))
out = ROOT/'Verification/AllImports.lean'
if args.check:
    if not out.exists() or out.read_text() != text:
        raise SystemExit('Run python3 scripts/update_verification_imports.py')
else:
    out.write_text(text)
